add state machine with test

diff --git a/build b/build
--- a/build
+++ b/build
@@ -27,16 +27,25 @@ if [ -n "${1+x}" ]; then
             make_all
             echo ""
 
-            test_bin="./out/bin/${2}"
-            if [ ! -f "$test_bin" ]; then
-                echo "ERROR: The executable ${test_bin} was not found."
-                echo ""
-                exit 1
-            fi
+            if [ "$2" == "all" ]; then
+                for file in ${build_dir}/bin/*
+                do
+                    echo ">> Running $(basename $file) test <<"
+                    $file
+                    echo ""
+                done
+            else
+                test_bin="${build_dir}/bin/${2}"
+                if [ ! -f "$test_bin" ]; then
+                    echo "ERROR: The executable ${test_bin} was not found."
+                    echo ""
+                    exit 1
+                fi
 
-            echo ">> Running ${2} test <<"
-            $test_bin
-            echo ""
+                echo ">> Running ${2} test <<"
+                $test_bin
+                echo ""
+            fi
             ;;
         "debug")
             echo ">> Building <<"
